// <auto-generated />
namespace LastPractice_B4_Test_allFrameworks.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class WaitersTableMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WaitersTableMig));
        
        string IMigrationMetadata.Id
        {
            get { return "202201181553467_WaitersTableMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
